#!/usr/bin/perl -w
# This script generates the entry of the system-call in user/usys.S!
# Run `make qemu`, Makefile will generate user/usys.S
# NOTE: The assembly code in usys.S exists in user space.
# Each time user calls a function like trace(), it would call the assembly code
# The user code traps into the kernel via `ecall` in usys.S
# Amazing!

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
entry("sysinfo");
